# Generated by Django 4.0.6 on 2022-07-28 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpnj', models.IntegerField(verbose_name=13)),
            ],
            options={
                'db_table': 'dados',
            },
        ),
    ]
