# Generated by Django 4.0.6 on 2022-07-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados',
            name='cpnj',
            field=models.IntegerField(),
        ),
    ]
