# Generated by Django 4.0.6 on 2022-07-28 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_dados_cpnj'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dados',
            table=None,
        ),
    ]
