# Generated by Django 4.0.6 on 2022-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_dados_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='nome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
