# Generated by Django 4.0.6 on 2022-07-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_dados_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Espacos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descrição', models.TextField(max_length=1000)),
                ('imagem1', models.ImageField(blank=True, upload_to='fotos/espacos')),
                ('imagem2', models.ImageField(blank=True, upload_to='fotos/espacos')),
                ('imagem3', models.ImageField(blank=True, upload_to='fotos/espacos')),
                ('imagem4', models.ImageField(blank=True, upload_to='fotos/espacos')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente', models.CharField(max_length=30)),
                ('mantenedor', models.CharField(choices=[('Mantenedor', 'Mantenedor'), ('Residente Startup', 'Residente Startup'), ('Time Operacional', 'Time Operacional')], max_length=30)),
                ('empresa', models.CharField(max_length=30)),
                ('evento', models.CharField(choices=[('Espaço01', 'Espaço01'), ('Espaço02', 'Espaço02'), ('Espaço03', 'Espaço03')], max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=1000)),
                ('check_in', models.BooleanField(default=False)),
                ('check_in_horario', models.TimeField()),
                ('check_out', models.BooleanField(default=False)),
                ('check_out_horario', models.TimeField()),
                ('participantes_presentes', models.IntegerField(default=0)),
            ],
        ),
    ]
