# Generated by Django 4.0.6 on 2022-07-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_rename_imagem1_espacos_imagem_um'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacos',
            old_name='imagem_um',
            new_name='imagem1',
        ),
    ]
