# Generated by Django 4.0.6 on 2022-07-29 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_alter_espacos_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacos',
            old_name='imagem',
            new_name='imagem1',
        ),
    ]
