# Generated by Django 4.0.6 on 2022-07-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_alter_espacos_imagem1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacos',
            name='imagem1',
            field=models.ImageField(blank=True, upload_to='fotos/espacos/imagem1'),
        ),
    ]
