# Generated by Django 4.0.6 on 2022-07-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_alter_espacos_imagem1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='espacos',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
