# Generated by Django 4.0.6 on 2022-08-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_alter_registro_check_in_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espacos',
            name='imagem2',
            field=models.ImageField(blank=True, upload_to='fotos/espacos/imagem2'),
        ),
        migrations.AlterField(
            model_name='espacos',
            name='imagem3',
            field=models.ImageField(blank=True, upload_to='fotos/espacos/imagem3'),
        ),
        migrations.AlterField(
            model_name='espacos',
            name='imagem4',
            field=models.ImageField(blank=True, upload_to='fotos/espacos/imagem4'),
        ),
    ]
