# Generated by Django 4.0.6 on 2022-08-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0018_alter_registro_check_in_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='check_in_horario',
            field=models.TimeField(default=''),
        ),
        migrations.AlterField(
            model_name='registro',
            name='check_out_horario',
            field=models.TimeField(default=''),
        ),
    ]
