# Generated by Django 4.0.6 on 2022-08-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0019_alter_espacos_imagem2_alter_espacos_imagem3_and_more'),
        ('registro', '0020_alter_registro_check_in_horario_and_more'),
    ]

    operations = [
    ]
