# Generated by Django 4.0.6 on 2022-08-13 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0022_nivelusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dados',
        ),
    ]
