# Generated by Django 4.0.6 on 2022-08-13 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0023_delete_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='data_reserva',
            field=models.DateField(default='2001-01-01', verbose_name='Data da Reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registro',
            name='hora_fim',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='Hora Fim'),
        ),
        migrations.AddField(
            model_name='registro',
            name='hora_inicio',
            field=models.TimeField(blank=True, default=datetime.time(0, 0), verbose_name='Hora Início'),
        ),
    ]
