# Generated by Django 4.0.6 on 2022-08-13 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0024_registro_data_reserva_registro_hora_fim_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registro',
            old_name='evento',
            new_name='espacos',
        ),
    ]
